.TH <tsvdb> 1 "<2011.07.21>" "" "Linux User's Manual"

.SH NAME
tsvdb \- Tab separated values database

.SH SYNOPSIS
.B tsvdb
[\fI-r|x|y|z|t|b|f|h|v\fR] [\fI-n{num}\fR]
[\fI-\fR[[\fIs|S\fR]|[\fIl|L\fR]]\fI{fstr}\fR]
[\fI-d{[,|;]}\fR] [\fItsvdatafile\fR]
.br
.br

 or
.B tsvdb
\fI-e|f\fR {\fIfile\fR}
.br

.SH DESCRIPTION
Simple textmode database program. Based on PDCurses TUIdemo sample.
The first line of the file defines the data structure.
Each tab-delimited word in the first line, defines a data field name and its length.
The number of lines up to one million, and a maximum number of fields is 16.

.SH OPTIONS
.IP \fB\-r\fR
Open in read-only.
.IP \fB\-x\fR
Readonly, but swiched back with Ctrl-X key.
.IP 	or	\fB\-X\fR
	Ro, can edit only current.
.IP \fB\-y\fR
Locked mode.
.IP \fB\-z\fR
Set safety on (alter Ctrl-Z).
.IP \fB\-a\fR
Set auto-seek off.
.IP \fB\-t\fR
Go to first record.
.IP \fB\-b\fR
Go bottom.
.IP \fB\-n\ recno\fR
Go to the n'th row.
.IP \fB\-s\ fstr\fR
Go to the first occurence of fstr.
.IP 	or	\fB\-s\ (fstr)\fR
	Search with Regular Expression.
.IP 	or	\fB\-S\ (fstr)\fR
	Search regexp to extract.
.IP \fB\-l\ str\fR
List of occurrences.
.IP 	or	\fB\-L\ str\fR
	List with header.
.IP \fB\-d\ chr\fR
Use separator (, or ;) char to CSV.
.IP \fB\-e\fR
Edit file as text.
.IP \fB\-f\fR
Set function key labels on.
.IP \fB\-p\fR
Parse file
.IP \fB\-h\fR
Syntax help.
.IP \fB\-v\fR
Print version.

.SH "SEE ALSO"
.SM
.IP http://tsvdb.sf.net/
.IP http://en.wikipedia.org/wiki/Tab-separated_values
